apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-pipeline-run-
spec:
  serviceAccountName: build-bot
  params:
    - name: app-name
      value: app-buildah
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/app-buildah-jklos
    - name: image-repo
      value: quay.io/juliaklos/app-buildah
  pipelineRef:
    name: build-pipeline
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce
